/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_admin_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_admin_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_api_admin_categories__category_id__get"];
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_admin_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Patch Category */
        patch: operations["patch_category_api_admin_categories__category_id__patch"];
        trace?: never;
    };
    "/api/admin/combos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Combos */
        get: operations["list_combos_api_admin_combos_get"];
        put?: never;
        /** Create Combo */
        post: operations["create_combo_api_admin_combos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/combos/{combo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Combo */
        get: operations["get_combo_api_admin_combos__combo_id__get"];
        put?: never;
        post?: never;
        /** Delete Combo */
        delete: operations["delete_combo_api_admin_combos__combo_id__delete"];
        options?: never;
        head?: never;
        /** Patch Combo */
        patch: operations["patch_combo_api_admin_combos__combo_id__patch"];
        trace?: never;
    };
    "/api/admin/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_admin_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/customers/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_admin_customers__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/customers/{user_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Customer */
        post: operations["lock_customer_api_admin_customers__user_id__lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/customers/{user_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock Customer */
        post: operations["unlock_customer_api_admin_customers__user_id__unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/import/pizzas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Pizzas */
        post: operations["import_pizzas_api_admin_import_pizzas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_admin_items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_admin_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/items/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_admin_items__product_id__get"];
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_admin_items__product_id__delete"];
        options?: never;
        head?: never;
        /** Patch Item */
        patch: operations["patch_item_api_admin_items__product_id__patch"];
        trace?: never;
    };
    "/api/admin/items/{product_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Item Image */
        post: operations["upload_item_image_api_admin_items__product_id__image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/items/{product_id}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item Options */
        get: operations["item_options_api_admin_items__product_id__options_get"];
        /** Replace Item Options */
        put: operations["replace_item_options_api_admin_items__product_id__options_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/option-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_admin_option_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_admin_option_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/option-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_admin_option_groups__group_id__delete"];
        options?: never;
        head?: never;
        /** Patch Group */
        patch: operations["patch_group_api_admin_option_groups__group_id__patch"];
        trace?: never;
    };
    "/api/admin/option-groups/{group_id}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Option */
        post: operations["create_option_api_admin_option_groups__group_id__options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/options/{option_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Option */
        delete: operations["delete_option_api_admin_options__option_id__delete"];
        options?: never;
        head?: never;
        /** Patch Option */
        patch: operations["patch_option_api_admin_options__option_id__patch"];
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_admin_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_admin_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Order */
        post: operations["cancel_order_api_admin_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{order_id}/retry-dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Dispatch
         * @description Hand a DispatchPending order to the delivery provider.
         *
         *     On success: store the reference and advance to Delivering. On provider
         *     failure: leave the order in DispatchPending so the admin can retry, and 502.
         */
        post: operations["retry_dispatch_api_admin_orders__order_id__retry_dispatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales Report */
        get: operations["sales_report_api_admin_reports_sales_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/sales.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales Report Csv */
        get: operations["sales_report_csv_api_admin_reports_sales_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_auth_me_patch"];
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote Cart */
        post: operations["quote_cart_api_cart_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Combos */
        get: operations["list_combos_api_combos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delivery Config */
        get: operations["delivery_config_api_config_delivery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/loyalty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loyalty Config */
        get: operations["loyalty_config_api_config_loyalty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_items__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/orders/{order_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Order
         * @description K2: Received -> Preparing.
         */
        post: operations["accept_order_api_kitchen_orders__order_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/orders/{order_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Ready
         * @description K3 + T1: Preparing -> ReadyForDispatch, then hand off to delivery.
         *
         *     Success advances to Delivering with a stored reference. A provider failure
         *     parks the order in DispatchPending for an admin retry (no 5xx — the order is
         *     safely captured and the kitchen's job is done).
         */
        post: operations["mark_ready_api_kitchen_orders__order_id__ready_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kitchen Queue */
        get: operations["kitchen_queue_api_kitchen_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loyalty/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loyalty Me */
        get: operations["loyalty_me_api_loyalty_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Order */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Orders */
        get: operations["my_orders_api_orders_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/track/{order_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Order */
        get: operations["track_order_api_orders_track__order_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delivery Webhook */
        post: operations["delivery_webhook_api_webhooks_delivery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthUserDTO */
        AuthUserDTO: {
            /** Address */
            address: string | null;
            /** Full Name */
            full_name: string;
            /** Phone Number */
            phone_number: string;
            role: components["schemas"]["UserRole"];
            /** User Id */
            user_id: number;
        };
        /** Body_import_pizzas_api_admin_import_pizzas_post */
        Body_import_pizzas_api_admin_import_pizzas_post: {
            /** File */
            file: string;
        };
        /** Body_upload_item_image_api_admin_items__product_id__image_post */
        Body_upload_item_image_api_admin_items__product_id__image_post: {
            /** Image */
            image: string;
        };
        /** CartQuoteIn */
        CartQuoteIn: {
            address?: components["schemas"]["QuoteAddressIn"] | null;
            /** Lines */
            lines: components["schemas"]["QuoteLineIn"][];
            /**
             * Redeem Points
             * @default 0
             */
            redeem_points: number;
        };
        /** CartQuoteOut */
        CartQuoteOut: {
            /** Delivery Fee Vnd */
            delivery_fee_vnd: number;
            /** Discount Combo Vnd */
            discount_combo_vnd: number;
            /** Discount Loyalty Vnd */
            discount_loyalty_vnd: number;
            loyalty: components["schemas"]["QuoteLoyaltyOut"];
            /** Subtotal Vnd */
            subtotal_vnd: number;
            /** Total Vnd */
            total_vnd: number;
        };
        /** CategoryIn */
        CategoryIn: {
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Name */
            name: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Category Id */
            category_id: number;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Sort Order */
            sort_order: number;
        };
        /** CategoryPatch */
        CategoryPatch: {
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** ComboIn */
        ComboIn: {
            /** Combo Price Vnd */
            combo_price_vnd: number;
            /** Description */
            description?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["ComboItemIn"][];
            /** Name */
            name: string;
            /** Target Group */
            target_group?: number | null;
            /** Validity End */
            validity_end?: string | null;
            /** Validity Start */
            validity_start?: string | null;
        };
        /** ComboItemIn */
        ComboItemIn: {
            /** Product Id */
            product_id: number;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** ComboItemOut */
        ComboItemOut: {
            /** Name */
            name: string;
            /** Product Id */
            product_id: number;
            /** Quantity */
            quantity: number;
        };
        /** ComboOut */
        ComboOut: {
            /** Combo Id */
            combo_id: number;
            /** Combo Price Vnd */
            combo_price_vnd: number;
            /** Description */
            description: string | null;
            /** Items */
            items: components["schemas"]["ComboItemOut"][];
            /** Name */
            name: string;
            status: components["schemas"]["ComboStatus"];
            /** Target Group */
            target_group: number | null;
            /** Validity End */
            validity_end: string | null;
            /** Validity Start */
            validity_start: string | null;
        };
        /** ComboPatch */
        ComboPatch: {
            /** Combo Price Vnd */
            combo_price_vnd?: number | null;
            /** Description */
            description?: string | null;
            /** Items */
            items?: components["schemas"]["ComboItemIn"][] | null;
            /** Name */
            name?: string | null;
            /** Target Group */
            target_group?: number | null;
            /** Validity End */
            validity_end?: string | null;
            /** Validity Start */
            validity_start?: string | null;
        };
        /**
         * ComboStatus
         * @enum {string}
         */
        ComboStatus: "Scheduled" | "Active" | "Expired";
        /** CustomerDetailOut */
        CustomerDetailOut: {
            /** Address */
            address: string | null;
            /** Current Points */
            current_points: number;
            /** Email */
            email: string | null;
            /** Full Name */
            full_name: string;
            /** Is Locked */
            is_locked: boolean;
            /** Membership Tier */
            membership_tier: string;
            /** Order Count */
            order_count: number;
            /** Phone Number */
            phone_number: string;
            /** User Id */
            user_id: number;
        };
        /** CustomerOut */
        CustomerOut: {
            /** Current Points */
            current_points: number;
            /** Email */
            email: string | null;
            /** Full Name */
            full_name: string;
            /** Is Locked */
            is_locked: boolean;
            /** Membership Tier */
            membership_tier: string;
            /** Order Count */
            order_count: number;
            /** Phone Number */
            phone_number: string;
            /** User Id */
            user_id: number;
        };
        /** DayRevenueOut */
        DayRevenueOut: {
            /** Day */
            day: string;
            /** Order Count */
            order_count: number;
            /** Revenue Vnd */
            revenue_vnd: number;
        };
        /** DeliveryConfigOut */
        DeliveryConfigOut: {
            /** Fee Vnd */
            fee_vnd: number;
            /** Service Area */
            service_area: string[];
        };
        /** GroupIn */
        GroupIn: {
            /** Name */
            name: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Select Type
             * @default multi
             * @enum {string}
             */
            select_type: "single" | "multi";
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** GroupOut */
        GroupOut: {
            /** Group Id */
            group_id: number;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /**
             * Select Type
             * @enum {string}
             */
            select_type: "single" | "multi";
            /** Sort Order */
            sort_order: number;
        };
        /** GroupPatch */
        GroupPatch: {
            /** Name */
            name?: string | null;
            /** Required */
            required?: boolean | null;
            /** Select Type */
            select_type?: ("single" | "multi") | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryOrderOut */
        HistoryOrderOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Status */
            current_status: string;
            /** Items */
            items: components["schemas"]["TrackItemOut"][];
            /** Order Code */
            order_code: string;
            /** Order Id */
            order_id: number;
            /** Total Amount Vnd */
            total_amount_vnd: number;
        };
        /** ImportSummary */
        ImportSummary: {
            /** Created */
            created: number;
            /** Errors */
            errors: string[];
            /** Skipped */
            skipped: number;
            /** Updated */
            updated: number;
        };
        /** ItemIn */
        ItemIn: {
            /** Base Price Vnd */
            base_price_vnd: number;
            /** Category Id */
            category_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pizza" | "side";
            /** Name */
            name: string;
        };
        /** ItemOptionGroupOut */
        ItemOptionGroupOut: {
            /** Group Id */
            group_id: number;
            /** Name */
            name: string;
            /** Options */
            options: components["schemas"]["ItemOptionOut"][];
            /** Required */
            required: boolean;
            /**
             * Select Type
             * @enum {string}
             */
            select_type: "single" | "multi";
            /** Sort Order */
            sort_order: number;
        };
        /** ItemOptionOut */
        ItemOptionOut: {
            /** Description */
            description?: string | null;
            /** Enabled */
            enabled: boolean;
            /** Name */
            name: string;
            /** Option Id */
            option_id: number;
            /** Price Delta Vnd */
            price_delta_vnd: number;
            /** Sort Order */
            sort_order: number;
        };
        /** ItemOptionsPut */
        ItemOptionsPut: {
            /** Option Ids */
            option_ids: number[];
        };
        /** ItemOut */
        ItemOut: {
            /** Base Price Vnd */
            base_price_vnd: number;
            /** Category Id */
            category_id: number;
            /** Image Url */
            image_url?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Is Pizza */
            is_pizza: boolean;
            /** Name */
            name: string;
            /** Product Id */
            product_id: number;
        };
        /** ItemPatch */
        ItemPatch: {
            /** Base Price Vnd */
            base_price_vnd?: number | null;
            /** Category Id */
            category_id?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** KitchenActionOut */
        KitchenActionOut: {
            /** Current Status */
            current_status: string;
            /** Order Code */
            order_code: string;
            /** Order Id */
            order_id: number;
        };
        /** LockIn */
        LockIn: {
            /** Reason */
            reason?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Phone Number */
            phone_number: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["AuthUserDTO"];
        };
        /** LoyaltyConfigOut */
        LoyaltyConfigOut: {
            /** Accrual Rate */
            accrual_rate: number;
            /** Max Redeem Pct */
            max_redeem_pct: number;
            /** Redeem Value Vnd */
            redeem_value_vnd: number;
        };
        /** LoyaltyMeResponse */
        LoyaltyMeResponse: {
            /** Current Points */
            current_points: number;
            /** Total Points Earned */
            total_points_earned: number;
        };
        /** MeResponse */
        MeResponse: {
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["AuthUserDTO"];
        };
        /** MenuCategoryOut */
        MenuCategoryOut: {
            /** Category Id */
            category_id: number;
            /** Name */
            name: string;
            /** Sort Order */
            sort_order: number;
        };
        /** MenuItemDetailOut */
        MenuItemDetailOut: {
            /** Base Price Vnd */
            base_price_vnd: number;
            /** Category Id */
            category_id: number;
            /** Image Url */
            image_url?: string | null;
            /** Is Pizza */
            is_pizza: boolean;
            /** Name */
            name: string;
            /**
             * Option Groups
             * @default []
             */
            option_groups: components["schemas"]["MenuOptionGroupOut"][];
            /** Product Id */
            product_id: number;
        };
        /** MenuItemOut */
        MenuItemOut: {
            /** Base Price Vnd */
            base_price_vnd: number;
            /** Category Id */
            category_id: number;
            /** Image Url */
            image_url?: string | null;
            /** Is Pizza */
            is_pizza: boolean;
            /** Name */
            name: string;
            /** Product Id */
            product_id: number;
        };
        /** MenuOptionGroupOut */
        MenuOptionGroupOut: {
            /** Group Id */
            group_id: number;
            /** Name */
            name: string;
            /** Options */
            options: components["schemas"]["MenuOptionOut"][];
            /** Required */
            required: boolean;
            /**
             * Select Type
             * @enum {string}
             */
            select_type: "single" | "multi";
        };
        /** MenuOptionOut */
        MenuOptionOut: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Option Id */
            option_id: number;
            /** Price Delta Vnd */
            price_delta_vnd: number;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** OptionIn */
        OptionIn: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /**
             * Price Delta Vnd
             * @default 0
             */
            price_delta_vnd: number;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** OptionOut */
        OptionOut: {
            /** Description */
            description?: string | null;
            /** Group Id */
            group_id: number;
            /** Name */
            name: string;
            /** Option Id */
            option_id: number;
            /** Price Delta Vnd */
            price_delta_vnd: number;
            /** Sort Order */
            sort_order: number;
        };
        /** OptionPatch */
        OptionPatch: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Price Delta Vnd */
            price_delta_vnd?: number | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** OrderAddressIn */
        OrderAddressIn: {
            /** Administrative Unit */
            administrative_unit: string;
            /** Street */
            street: string;
        };
        /** OrderCancelIn */
        OrderCancelIn: {
            /** Reason */
            reason?: string | null;
        };
        /** OrderLineIn */
        OrderLineIn: {
            /** Combo Id */
            combo_id?: number | null;
            /** Item Id */
            item_id?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "item" | "combo";
            /** Notes */
            notes?: string | null;
            /** Option Ids */
            option_ids?: number[];
            /** Quantity */
            quantity: number;
        };
        /** OrderSummaryOut */
        OrderSummaryOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Status */
            current_status: string;
            /** Delivery Address */
            delivery_address: string;
            /** Order Code */
            order_code: string;
            /** Order Id */
            order_id: number;
            /** Recipient Name */
            recipient_name: string;
            /** Recipient Phone */
            recipient_phone: string;
            /** Total Amount Vnd */
            total_amount_vnd: number;
            /** User Id */
            user_id: number | null;
        };
        /** PlaceOrderIn */
        PlaceOrderIn: {
            address: components["schemas"]["OrderAddressIn"];
            /** Delivery Note */
            delivery_note?: string | null;
            /** Lines */
            lines: components["schemas"]["OrderLineIn"][];
            /** Recipient Name */
            recipient_name: string;
            /** Recipient Phone */
            recipient_phone: string;
            /**
             * Redeem Points
             * @default 0
             */
            redeem_points: number;
        };
        /** PlaceOrderOut */
        PlaceOrderOut: {
            /** Current Status */
            current_status: string;
            /** Delivery Fee Vnd */
            delivery_fee_vnd: number;
            /** Loyalty Redeemed */
            loyalty_redeemed: number;
            /** Order Code */
            order_code: string;
            /** Order Id */
            order_id: number;
            /** Total Amount Vnd */
            total_amount_vnd: number;
        };
        /** PublicComboItemOut */
        PublicComboItemOut: {
            /** Base Price Vnd */
            base_price_vnd: number;
            /** Image Url */
            image_url?: string | null;
            /** Name */
            name: string;
            /** Product Id */
            product_id: number;
            /** Quantity */
            quantity: number;
        };
        /** PublicComboOut */
        PublicComboOut: {
            /** Combo Id */
            combo_id: number;
            /** Combo Price Vnd */
            combo_price_vnd: number;
            /** Description */
            description?: string | null;
            /** Items */
            items: components["schemas"]["PublicComboItemOut"][];
            /** Items Total Vnd */
            items_total_vnd: number;
            /** Name */
            name: string;
            /** Savings Vnd */
            savings_vnd: number;
            /** Target Group */
            target_group?: number | null;
        };
        /** QueueItemOut */
        QueueItemOut: {
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Quantity */
            quantity: number;
        };
        /** QueueOrderOut */
        QueueOrderOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Status */
            current_status: string;
            /** Items */
            items: components["schemas"]["QueueItemOut"][];
            /** Order Code */
            order_code: string;
            /** Order Id */
            order_id: number;
            /**
             * Promised At
             * Format: date-time
             */
            promised_at: string;
        };
        /** QuoteAddressIn */
        QuoteAddressIn: {
            /** Administrative Unit */
            administrative_unit: string;
            /** Street */
            street?: string | null;
        };
        /** QuoteLineIn */
        QuoteLineIn: {
            /** Combo Id */
            combo_id?: number | null;
            /** Item Id */
            item_id?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "item" | "combo";
            /** Option Ids */
            option_ids?: number[];
            /** Quantity */
            quantity: number;
        };
        /** QuoteLoyaltyOut */
        QuoteLoyaltyOut: {
            /** Balance */
            balance: number;
            /** Max Redeemable */
            max_redeemable: number;
            /** Redeemed */
            redeemed: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Address */
            address?: string | null;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
            /** Phone Number */
            phone_number: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            user: components["schemas"]["AuthUserDTO"];
        };
        /** SalesReportOut */
        SalesReportOut: {
            /** Average Order Value Vnd */
            average_order_value_vnd: number;
            /** Date From */
            date_from: string;
            /** Date To */
            date_to: string;
            /** Delivered Order Count */
            delivered_order_count: number;
            /** Orders By Status */
            orders_by_status: components["schemas"]["StatusCountOut"][];
            /** Revenue By Day */
            revenue_by_day: components["schemas"]["DayRevenueOut"][];
            /** Top Items */
            top_items: components["schemas"]["TopItemOut"][];
            /** Total Order Count */
            total_order_count: number;
            /** Total Revenue Vnd */
            total_revenue_vnd: number;
        };
        /** StatusCountOut */
        StatusCountOut: {
            /** Count */
            count: number;
            /** Status */
            status: string;
        };
        /** TopItemOut */
        TopItemOut: {
            /** Name */
            name: string;
            /** Quantity Sold */
            quantity_sold: number;
            /** Revenue Vnd */
            revenue_vnd: number;
        };
        /** TrackEventOut */
        TrackEventOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Note */
            note: string | null;
            /** Status */
            status: string;
        };
        /** TrackItemOut */
        TrackItemOut: {
            /** Name */
            name: string;
            /** Options */
            options: components["schemas"]["TrackOptionOut"][];
            /** Quantity */
            quantity: number;
            /** Unit Price Vnd */
            unit_price_vnd: number;
        };
        /** TrackOptionOut */
        TrackOptionOut: {
            /** Group Name */
            group_name: string;
            /** Option Name */
            option_name: string;
        };
        /** TrackOrderOut */
        TrackOrderOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Status */
            current_status: string;
            /** Delivery Address */
            delivery_address: string;
            /** Delivery Fee Vnd */
            delivery_fee_vnd: number;
            /** Items */
            items: components["schemas"]["TrackItemOut"][];
            /** Order Code */
            order_code: string;
            /**
             * Promised At
             * Format: date-time
             */
            promised_at: string;
            /** Recipient Name */
            recipient_name: string;
            /** Timeline */
            timeline: components["schemas"]["TrackEventOut"][];
            /** Total Amount Vnd */
            total_amount_vnd: number;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Address */
            address?: string | null;
            /** Full Name */
            full_name?: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "customer" | "admin" | "kitchen";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_categories_api_admin_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    create_category_api_admin_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_api_admin_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_admin_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_category_api_admin_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_combos_api_admin_combos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComboOut"][];
                };
            };
        };
    };
    create_combo_api_admin_combos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComboIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComboOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_combo_api_admin_combos__combo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                combo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComboOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_combo_api_admin_combos__combo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                combo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_combo_api_admin_combos__combo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                combo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComboPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComboOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_admin_customers_get: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_admin_customers__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_customer_api_admin_customers__user_id__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_customer_api_admin_customers__user_id__unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_pizzas_api_admin_import_pizzas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_pizzas_api_admin_import_pizzas_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_admin_items_get: {
        parameters: {
            query?: {
                kind?: ("pizza" | "side") | null;
                category_id?: number | null;
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_admin_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_admin_items__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_admin_items__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_item_api_admin_items__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_item_image_api_admin_items__product_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_item_image_api_admin_items__product_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_options_api_admin_items__product_id__options_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOptionGroupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_item_options_api_admin_items__product_id__options_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemOptionsPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOptionGroupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_admin_option_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"][];
                };
            };
        };
    };
    create_group_api_admin_option_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_admin_option_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_group_api_admin_option_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_option_api_admin_option_groups__group_id__options_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_option_api_admin_options__option_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                option_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_option_api_admin_options__option_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                option_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_admin_orders_get: {
        parameters: {
            query?: {
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_admin_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_admin_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCancelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_dispatch_api_admin_orders__order_id__retry_dispatch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sales_report_api_admin_reports_sales_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sales_report_csv_api_admin_reports_sales_csv_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_api_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_cart_api_cart_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartQuoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartQuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuCategoryOut"][];
                };
            };
        };
    };
    list_combos_api_combos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicComboOut"][];
                };
            };
        };
    };
    delivery_config_api_config_delivery_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryConfigOut"];
                };
            };
        };
    };
    loyalty_config_api_config_loyalty_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoyaltyConfigOut"];
                };
            };
        };
    };
    list_items_api_items_get: {
        parameters: {
            query?: {
                category?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_items__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_order_api_kitchen_orders__order_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KitchenActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_ready_api_kitchen_orders__order_id__ready_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KitchenActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kitchen_queue_api_kitchen_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueOrderOut"][];
                };
            };
        };
    };
    loyalty_me_api_loyalty_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoyaltyMeResponse"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceOrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceOrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_orders_api_orders_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOrderOut"][];
                };
            };
        };
    };
    track_order_api_orders_track__order_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delivery_webhook_api_webhooks_delivery_post: {
        parameters: {
            query?: never;
            header: {
                "X-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
